# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  app_id: 148439841877340
  secret: dba136f9ebe98c81a9acd063ab3ac3ee
  api_key: ab10621e6477ea9b6a5ccf27d65f5f40

production:
  app_id: 138352476218334
  secret: 1020ef35d9774ff638d1656a263d8182
  api_key: 27a7a8b0b1687813aadaa8075783e871

test:
  app_id: 138352476218334
  secret: 1020ef35d9774ff638d1656a263d8182
  api_key: 27a7a8b0b1687813aadaa8075783e871